"""Pre-build Cost Estimation -- estimate monthly costs and generate Terraform scaffolds."""

from __future__ import annotations

import json
from typing import Any

from botocore.exceptions import BotoCoreError, ClientError

from ..auth import get_client
from ..scan_contract import error_result, ok_result, scan_error_from_exception
from ..types import CostEstimate, ResourceEstimate, ScanResult

_SUPPORTED_TYPES = {"ec2", "rds", "lambda", "s3", "nat_gateway", "load_balancer"}

_HOURS_PER_MONTH = 730


# ---------------------------------------------------------------------------
# Pricing helpers
# ---------------------------------------------------------------------------


def _get_ec2_price(pricing_client: object, instance_type: str) -> float | None:
    """Look up on-demand hourly price for an EC2 instance type via the Pricing API.

    Returns ``None`` when the price cannot be determined.
    """
    try:
        response = pricing_client.get_products(  # type: ignore[attr-defined]
            ServiceCode="AmazonEC2",
            Filters=[
                {"Type": "EQUALS", "Field": "instanceType", "Value": instance_type},
                {"Type": "EQUALS", "Field": "operatingSystem", "Value": "Linux"},
                {"Type": "EQUALS", "Field": "tenancy", "Value": "Shared"},
                {"Type": "EQUALS", "Field": "preInstalledSw", "Value": "NA"},
                {"Type": "EQUALS", "Field": "capacitystatus", "Value": "Used"},
            ],
            MaxResults=10,
        )
        for price_str in response.get("PriceList", []):
            price_item = json.loads(price_str)
            od = price_item.get("terms", {}).get("OnDemand", {})
            for term in od.values():
                for dim in term.get("priceDimensions", {}).values():
                    price = float(dim["pricePerUnit"].get("USD", "0"))
                    if price > 0:
                        return price
        return None
    except (ClientError, BotoCoreError, KeyError, ValueError, json.JSONDecodeError):
        return None


def _get_rds_price(pricing_client: object, instance_class: str) -> float | None:
    """Look up on-demand hourly price for an RDS instance class via the Pricing API.

    Assumes MySQL Single-AZ. Returns ``None`` when the price cannot be determined.
    """
    try:
        response = pricing_client.get_products(  # type: ignore[attr-defined]
            ServiceCode="AmazonRDS",
            Filters=[
                {"Type": "EQUALS", "Field": "instanceType", "Value": instance_class},
                {"Type": "EQUALS", "Field": "databaseEngine", "Value": "MySQL"},
                {
                    "Type": "EQUALS",
                    "Field": "deploymentOption",
                    "Value": "Single-AZ",
                },
            ],
            MaxResults=10,
        )
        for price_str in response.get("PriceList", []):
            price_item = json.loads(price_str)
            od = price_item.get("terms", {}).get("OnDemand", {})
            for term in od.values():
                for dim in term.get("priceDimensions", {}).values():
                    price = float(dim["pricePerUnit"].get("USD", "0"))
                    if price > 0:
                        return price
        return None
    except (ClientError, BotoCoreError, KeyError, ValueError, json.JSONDecodeError):
        return None


# ---------------------------------------------------------------------------
# Terraform scaffold generator
# ---------------------------------------------------------------------------

_TF_HEADER = """\
# Terraform scaffold generated by AWS Lighthouse
# Review and customise before applying
"""

_TF_EC2 = """\
resource "aws_instance" "app" {{
  count         = {count}
  ami           = "ami-0c55b159cbfafe1f0"  # Amazon Linux 2 (update for your region)
  instance_type = "{instance_type}"

  tags = {{
    Name = "app-${{count.index}}"
  }}
}}
"""

_TF_RDS = """\
resource "aws_db_instance" "database" {{
  count              = {count}
  identifier         = "database-${{count.index}}"
  engine             = "mysql"
  engine_version     = "8.0"
  instance_class     = "{instance_class}"
  allocated_storage  = 20
  username           = "admin"
  password           = var.db_password
  skip_final_snapshot = true
}}
"""

_TF_LAMBDA = """\
resource "aws_lambda_function" "fn" {{
  count         = {count}
  function_name = "function-${{count.index}}"
  runtime       = "python3.12"
  handler       = "handler.lambda_handler"
  role          = aws_iam_role.lambda_exec.arn
  filename      = "function.zip"
}}
"""

_TF_NAT = """\
resource "aws_nat_gateway" "nat" {{
  count         = {count}
  allocation_id = aws_eip.nat[count.index].id
  subnet_id     = aws_subnet.public[count.index].id
}}
"""

_TF_ALB = """\
resource "aws_lb" "alb" {{
  count              = {count}
  name               = "alb-${{count.index}}"
  internal           = false
  load_balancer_type = "application"
  subnets            = aws_subnet.public[*].id
}}
"""

_TF_S3 = """\
resource "aws_s3_bucket" "bucket" {{
  count  = {count}
  bucket = "my-bucket-${{count.index}}-${{random_id.suffix.hex}}"
}}
"""


def _generate_terraform(resources: list[dict[str, Any]]) -> str:
    """Generate a basic HCL scaffold for the given resource list."""
    blocks: list[str] = [_TF_HEADER]
    for spec in resources:
        rtype = str(spec.get("type", "")).lower()
        count = int(spec.get("count", 1))
        instance_type = str(spec.get("instance_type", "t3.micro"))
        instance_class = str(spec.get("instance_class", "db.t3.micro"))

        if rtype == "ec2":
            blocks.append(_TF_EC2.format(count=count, instance_type=instance_type))
        elif rtype == "rds":
            blocks.append(_TF_RDS.format(count=count, instance_class=instance_class))
        elif rtype == "lambda":
            blocks.append(_TF_LAMBDA.format(count=count))
        elif rtype == "nat_gateway":
            blocks.append(_TF_NAT.format(count=count))
        elif rtype == "load_balancer":
            blocks.append(_TF_ALB.format(count=count))
        elif rtype == "s3":
            blocks.append(_TF_S3.format(count=count))
    return "\n".join(blocks)


# ---------------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------------


def estimate_build_cost(
    resources: list[dict[str, Any]], region: str | None = None
) -> ScanResult:
    """Estimate monthly AWS costs and generate a Terraform scaffold.

    Args:
        resources: List of dicts with ``type``, ``count``, and optionally
            ``instance_type`` or ``instance_class``.
        region: Unused -- Pricing API is always queried in ``us-east-1``.

    Returns:
        ScanResult with ``data`` as a :class:`CostEstimate` dict.
    """
    try:
        pricing = get_client("pricing", "us-east-1")
    except (ClientError, BotoCoreError) as e:
        return error_result(
            data={},
            errors=[
                scan_error_from_exception(
                    service="pricing",
                    operation="CreateClient",
                    exc=e,
                )
            ],
        )

    estimates: list[ResourceEstimate] = []

    for spec in resources:
        rtype = str(spec.get("type", "")).lower()
        count = int(spec.get("count", 1))
        if rtype not in _SUPPORTED_TYPES:
            continue

        unit_monthly_cost: float | None = None
        label: str = ""
        pricing_note: str = ""

        if rtype == "ec2":
            instance_type = str(spec.get("instance_type", "t3.micro"))
            hourly = _get_ec2_price(pricing, instance_type)
            if hourly is not None:
                unit_monthly_cost = round(hourly * _HOURS_PER_MONTH, 2)
            label = f"{instance_type} x{count}"
            pricing_note = "on-demand Linux" if hourly else "price unavailable"

        elif rtype == "rds":
            instance_class = str(
                spec.get("instance_class", spec.get("db_instance_class", "db.t3.micro"))
            )
            hourly = _get_rds_price(pricing, instance_class)
            if hourly is not None:
                unit_monthly_cost = round(hourly * _HOURS_PER_MONTH, 2)
            label = f"{instance_class} x{count}"
            pricing_note = (
                "on-demand MySQL Single-AZ" if hourly else "price unavailable"
            )

        elif rtype == "lambda":
            unit_monthly_cost = 5.0
            label = f"Lambda x{count}"
            pricing_note = "estimated (pay-per-use; actual varies)"

        elif rtype == "nat_gateway":
            unit_monthly_cost = 35.0
            label = f"NAT Gateway x{count}"
            pricing_note = "hourly charge only; data transfer extra"

        elif rtype == "load_balancer":
            unit_monthly_cost = 22.50
            label = f"ALB x{count}"
            pricing_note = "base hourly; LCU charges extra"

        elif rtype == "s3":
            unit_monthly_cost = None
            label = f"S3 bucket x{count}"
            pricing_note = "bucket cost: $0.023/GB/month (size unknown)"

        total_monthly_cost = (
            round(unit_monthly_cost * count, 2)
            if unit_monthly_cost is not None
            else None
        )

        estimates.append(
            {
                "resource_type": rtype,
                "label": label,
                "count": count,
                "unit_monthly_cost": unit_monthly_cost,
                "total_monthly_cost": total_monthly_cost,
                "pricing_note": pricing_note,
            }
        )

    # Totals (only where cost is known)
    known_costs = [
        e["total_monthly_cost"]
        for e in estimates
        if e["total_monthly_cost"] is not None
    ]
    total_monthly = sum(known_costs) if known_costs else None
    total_annual = round(total_monthly * 12, 2) if total_monthly is not None else None

    scaffold = _generate_terraform(resources)

    result: CostEstimate = {
        "resources": estimates,
        "total_monthly_cost": (
            round(total_monthly, 2) if total_monthly is not None else None
        ),
        "total_annual_cost": total_annual,
        "terraform_scaffold": scaffold,
        "currency": "USD",
    }
    return ok_result(result)
